name: CI
on:
  - push
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        id: go
        with:
          go-version: '^1.15.0'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          $env:Path = "$env:WIX\bin;$env:Path"
          go run make.go

      - name: Prepare artifacts
        run: |
          mkdir artifacts
          cp just-install.exe artifacts
          cp just-install.msi artifacts

      - name: Upload just-install.exe
        uses: actions/upload-artifact@v2
        with:
          name: just-install.exe
          path: artifacts/just-install.exe

      - name: Upload just-install.msi
        uses: actions/upload-artifact@v2
        with:
          name: just-install.msi
          path: artifacts/just-install.msi
